<ComboBoxButton@Button>:
    font_size: 11
    width: 200
    size_hint: (.6, 1)

<ComboBoxLabels@Label>:
    font_size: 11
    size_hint: (.4, 1)

<VocoderView>:
    id: vocoderView
    rows: 2
    columns: 2
    padding: 10
    spacing: 10
    input_devices_button: input_devices_button
    output_devices_button: output_devices_button
    carrier_source_button: carrier_source_button
    modulator_source_button: modulator_source_button

    BoxLayout:
        spacing: 30
        padding: 20
        orientation: "vertical"
        BoxLayout:
            ComboBoxLabels:
                text: "Input device"
            ComboBoxButton
                id: input_devices_button
                text: "choose device"

        BoxLayout:
            ComboBoxLabels:
                text: "Output device"
            ComboBoxButton
                id: output_devices_button
                text: "choose device"

        BoxLayout:
            ComboBoxLabels:
                text: "Carrier source"
            ComboBoxButton
                id: carrier_source_button
                text: "choose file"

        BoxLayout:
            ComboBoxLabels:
                text: "Modulator source"
            ComboBoxButton
                id: modulator_source_button
                text: "choose file"

    Label:
        text: "place for FFT"

    BoxLayout:
        orientation: "vertical"
        spacing: 30

        BoxLayout:
            Button:
                size_hint: (.7, .5)
                text: "Play"
                on_release: vocoderView.on_play()
            Button:
                size_hint: (.3, .5)
                text: "Stop"
                on_release: vocoderView.on_stop()

        ToggleButton:
            size_hint: (1, .5)
            text: "File"
            on_release: vocoderView.change_mode(self)

        ToggleButton:
            size_hint: (1, .5)
            text: "LPC"
            on_release: vocoderView.change_calc_strategy(self)

        Button:
            size_hint: (1, .5)
            text: "Settings"
            on_release: vocoderView.on_settings_click()
    Label:
        text: "place for FFT"


<LoadDialog>:
    BoxLayout:
        size: root.size
        pos: root.pos
        orientation: "vertical"
        FileChooserListView:
            id: filechooser

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Load"
                on_release: root.load(filechooser.path, filechooser.selection)

<SettingsWindowLPC>
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        BoxLayout:
            Label:

                text: "Chunk size"
            TextInput:
                size_hint: (.4, 1)
                id: chunk_size_val
                text: '512'

        BoxLayout:
            Label:
                text: 'Pre. emp. coef.'

            TextInput:
                size_hint: (.4, 1)
                id: pre_emp_val
                text: '0.95'

        BoxLayout:
            Label:
                text: 'Taps number'

            TextInput:
                size_hint: (.4, 1)
                id: n_taps_val
                text: '40'

        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Save"
                on_release: root.save(CHUNK=chunk_size_val.text, PRE_EMP_COEFF=pre_emp_val.text, N_TAPS=n_taps_val.text)


<SettingsWindowFFT>
    BoxLayout:
        orientation: "vertical"
        spacing: 10
        BoxLayout:
            Label:

                text: "Chunk size"
            TextInput:
                size_hint: (.4, 1)
                id: chunk_size_val
                text: '512'

        BoxLayout:
            Label:
                text: 'Pre. emp. coef.'

            TextInput:
                size_hint: (.4, 1)
                id: pre_emp_val
                text: '0.95'

        BoxLayout:
            Label:
                text: 'Filters number'

            TextInput:
                size_hint: (.4, 1)
                id: n_filts_val
                text: '40'

        BoxLayout:
            Label:
                text: 'Filter low'

            TextInput:
                size_hint: (.4, 1)
                id: filt_low_val
                text: '50'

        BoxLayout:
            Label:
                text: 'Filter up'

            TextInput:
                size_hint: (.4, 1)
                id: filt_up_val
                text: '10000'
        BoxLayout:
            size_hint_y: None
            height: 30
            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Save"
                on_release: root.save(CHUNK=chunk_size_val.text, PRE_EMP_COEFF=pre_emp_val.text, N_FILT=n_filts_val.text, FILT_LOW=filt_low_val, FILT_UP=filt_up_val)